### ISSUE TITLE
🐞 - `TuiDocDocumentationPropertyConnectorDirective` incorrectly parses dot from query params

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#3474]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-doc

### Is this issue blocking you?

Non-Blocking

### Description

Open https://tinkoff.github.io/maskito/kit/number/API?decimalSeparator=.&precision=2
Wait until page is loaded.
Look at url: https://tinkoff.github.io/maskito/kit/number/API?decimalSeparator=NaN&precision=2

`decimalSeparator`-query param becomes:  `decimalSeparator=NaN`

<img width="616" alt="Screenshot 2023-01-20 at 15 50 22" src="https://user-images.githubusercontent.com/35179038/213698986-0a8b13b5-48f1-4f81-85bd-3187bcc6038f.png">

### Angular version

12

### Taiga UI version

3.14.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed by https://github.com/Tinkoff/taiga-ui/pull/3439
update `addon-doc` to v3.16

**Comment by nsbarsukov** [comment]
My mistake, sorry)

**Comment by nsbarsukov** [comment]
@splincode I reopen issue because problem is still reproduced with `3.16.0`

**Comment by splincode** [comment]
@nsbarsukov sorry for that
